ALTER TABLE control_totals_maz DROP PRIMARY KEY, ADD CONSTRAINT PK PRIMARY KEY (REGION, PUMA, TAZ, MAZ);

ALTER TABLE control_totals_taz DROP PRIMARY KEY, ADD PRIMARY KEY (TAZ);


ALTER TABLE control_totals_meta DROP PRIMARY KEY, ADD PRIMARY KEY (region);